### ISSUE TITLE
docker images only support ARM64

### ISSUE THREAD

**Issue by 0xmoei** [ora-io/tora-docker-compose#11]
docker images only support ARM64. Add AMD64 please

**Comment by LiRiu** [comment]
Added. Good luck with everything!
[tora:confirm docker image in amd64 arch](https://hub.docker.com/layers/oraprotocol/tora/confirm/images/sha256-53928360fe05911b188ea398d19c3992959a95b1f84037b4f563d57d2d4ade44?context=repo)
